### ISSUE TITLE
AttributeError: '_UserType' object has no attribute 'type'

### ISSUE THREAD

**Issue by alexander-sung** [aiplan4eu/unified-planning#107]
**Describe the bug**
When using UP with the newest versions of unified-planning, pyperplan, and tamer, program execution of the UP example as below yields `AttributeError: '_UserType' object has no attribute 'type'` at line `move.add_precondition(at(x))`.

**To Reproduce**
```
#!/usr/bin/env python3
from unified_planning.model import Fluent, InstantaneousAction, Object, Problem
from unified_planning.shortcuts import BoolType, OneshotPlanner, UserType


Location = UserType("Location")
a, b = Object('a', Location), Object('b', Location)

at = Fluent("At", BoolType(), [Location])

move = InstantaneousAction("Move", x=Location, y=Location)
x, y = move.parameters()
move.add_precondition(at(x))
move.add_effect(at(x), False)
move.add_effect(at(y), True)

problem = Problem("Example")
problem.add_fluent(at, default_initial_value=False)
problem.add_action(move)
problem.add_objects([a, b])
problem.set_initial_value(at(a), True)
problem.add_goal(at(b))

with OneshotPlanner(problem_kind=problem.kind()) as planner:
    plan = planner.solve(problem)
    print(f"{planner.name()} returned: {plan}")
```

**Expected behavior**
Previously this and similar examples ran without problem. The last working commits for me are:
- unified-planning: 3b513d5
- up-pyperplan: a6aa9f2
- up-tamer: a1e3108

**Desktop:**
 - OS: Ubuntu 20.04

**Comment by alvalentini** [comment]
This is due to the fact that we changed the way you can create a `Fluent`.
Now you have to specify also the name of the parameters, not only the type.

In order to create the fluent `At` you can create it in one of the following way:

- `at = Fluent("At", BoolType(), loc=Location)`
- `at = Fluent("At", BoolType(), [Parameter('loc', Location)])`
- `at = Fluent("At", BoolType(), OrderedDict([('loc', Location)]))`

Let me know if this can solve your problem.

**Comment by mikand** [comment]
@alvalentini is right, however we should try to give a more meaningful error (if possible)

**Comment by alexander-sung** [comment]
Nice. Thank you very much for the quick reply, @alvalentini. I assumed it was an interface change but looked at the wrong place. With your directions it is now clear that the type parameters of a fluent shall have names, which was missing in my old example. Bear with me, I surely still have a lot to catch up and thus very welcome Andrea's suggestion.

**Comment by alexander-sung** [comment]
Nice. Thank you very much for the quick reply, @alvalentini. I assumed it was an interface change but looked at the wrong place. With your directions it is now clear that the type parameters of a fluent shall have names, which was missing in my old example. Bear with me, I surely still have a lot to catch up and thus very welcome Andrea's suggestion.

**Comment by alexander-sung** [comment]
Sorry, I have a follow-up on this: Is it important that the user is providing specific parameter names? I'm just updating my examples and at some point create generic names, e.g., `OrderedDict([(f"parameter{index}", Location) for index in range(3)])`. So, I wondered if this is something you wanted to avoid.

I guess it depends on whether the user wants to use these parameter names at some point and might wonder what they are.

**Comment by alvalentini** [comment]
The parameter names are useful for documentation reasons (similarly to PDDL): they can explain the semantic of the parameters.

They can make easier to understand the problem you are modeling, reading the python code you wrote.

**Comment by alexander-sung** [comment]
Makes sense. In my simple examples, it's rather obvious from the UserType but documentation is good. Many thanks again for your support! I really appreciate it.
