### ISSUE TITLE
Explain why no planner can handle the problem

### ISSUE THREAD

**Issue by alexander-sung** [aiplan4eu/unified-planning#108]
### User Story
As a **UP user** I want to receive information why none of my planners can solve the kind of problem I described, to reformulate the problem or find a suitable planner.

```
#!/usr/bin/env python3
from unified_planning.model import Fluent, InstantaneousAction, Object, Problem
from unified_planning.shortcuts import Equals, Not, OneshotPlanner, UserType


Location = UserType("Location")
a, b, c = locations = [Object(location, Location) for location in ('a', 'b', 'c')]

robot_at = Fluent("RobotAt", Location)

move = InstantaneousAction("Move", x=Location, y=Location)
x, y = move.parameters()
move.add_precondition(Equals(robot_at, x))
move.add_effect(robot_at, y, Not(Equals(robot_at, b)))

problem = Problem("Simple")
problem.add_fluent(robot_at, default_initial_value=a)
problem.add_action(move)
problem.add_objects(locations)
problem.add_goal(Equals(robot_at, c))

with OneshotPlanner(problem_kind=problem.kind()) as planner:
    plan = planner.solve(problem)
    print(f"{planner.name()} returned: {plan}")
```
In this small example, I use conditional planning for no reason in the effect of action `move`. Since none of my planners can handle this, I currently receive a `RuntimeError: No active exception to reraise`. A concrete error message is desired, ideally one explaining the missing feature of conditional planning in all of my available planners.

### Acceptance Criteria

- [ ] At least the error message shall state that no available planner can handle the problem kind.
- [ ] Optionally, if feasible, each planner returns one reason why it cannot handle the problem kind.
- [ ] Optionally, if feasible, each planner returns all reasons why it cannot handle the problem kind.

### Attention Points

Coincidentally, this request is related to our discussions yesterday regarding improved results from the planners. I'm not sure if this issue is handled within the improved design, so I'd like to bring it up here. From my understanding our discussions addressed the cases where a planner can handle the problem kind in principle but fails on the concrete problem instance, whereas for the problem in this issue no planner will actually run and give any result.

**Comment by mikand** [comment]
Thanks @alexander-sung !

I see two issues within this story:
1. Raise a meaningful exception, e.g. `NoSuitableSolverAvailableException` or similar
2. Try to explain which are the characteristics of the problem that are outside the capability of the installed solvers. This can be done by computing the "difference" between two problem kind, but we need to understand how to report this to the user.

I am putting this user story in the todo list of the project.

**Comment by alexander-sung** [comment]
Yes, agreed. Thanks, Andrea.

I don't know the details of a problem kind, so I wanted to leave the discussion open for possible solutions. From my understanding, it could be tricky to communicate that all necessary "features" can be handled by all planners together but no single one can handle all of them at the same time. Maybe I'm overthinking it for now, so I welcome your procedure.

**Comment by arbimo** [comment]
A possible presentation of this would be an ASCII table that presents the support of planners for the requested features.
This should allow the user identifying the allowed combination of features. E.g. something like so, with the first planner being the one with closest support:

| Planner | durative-action | numeric-precondition |
|------------|:--------------------:|:----------------------------:|
|  tamer   |  :heavy_check_mark:   | - |
| ENHSP | - | :heavy_check_mark:  |
| FD | - | - |
