### ISSUE TITLE
PDDLReader chokes on Miconic (fulladl)

### ISSUE THREAD

**Issue by roeger** [aiplan4eu/unified-planning#109]
When reading a (classical) Miconic problem in the full-adl version (attached), the PDDLReader throws a syntax error:

`SyntaxError: Not able to handle: ['when', ['and', ['boarded', '?p'], ['destin', '?p', '?f']], ['and', ['not', ['boarded', '?p']], ['served', '?p']]]
`

Here are the files (please remove suffix `txt`, I could not attach pddl files):
[domain.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/8357297/domain.pddl.txt)
[f2-4.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/8357298/f2-4.pddl.txt)

**To Reproduce**

```
from unified_planning.shortcuts import *
from unified_planning.io import PDDLWriter, PDDLReader
reader = PDDLReader()
problem = reader.parse_problem('domain.pddl', 'miconic-fulladl/f2-4.pddl')
```

**Comment by mikand** [comment]
Thanks for the report @roeger !

@alvalentini is looking into this, but the issue is that we currently we do not have quantifiers for effects at the moment, we only have quantifiers for conditions expressions. We will try to see how to deal with these
