### ISSUE TITLE
Python planner fails with non-python object names

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#111]
**Describe the bug**
When using the `PythonPrinter` on a problem that contains names (e.g. action names) that are not valid python names, the produced code is invalid.

**To Reproduce**
1. Create a problem with an action named `invalid-name`
2. Generate the python code using the `PythonPrinter` 
3. Try to execute the generated python code

**Expected behavior**
Python variables are "mangled" to form valid python names

**Comment by alvalentini** [comment]
This issue should be fixed in #119
