### ISSUE TITLE
Errors when using PythonWriter 

### ISSUE THREAD

**Issue by LBonassi95** [aiplan4eu/unified-planning#115]
**Describe the bug**
I have found 3 issues when using PythonWriter with the provided PDDL instance:
1. Some predicates have '-' in the name. The translation to python keeps the '-' in the python variables (see ```fluent_ready-to-load``` in the output file). This issue can also occur when '-' is in action names.
2. There is a missing newline here: ```problem_initial_defaults[tm.BoolType()] = emgr.FALSE()problem = up.model.Problem("TPP", env, initial_defaults=problem_initial_defaults)``` (line 27 of output)
3. See ```act_drive = up.model.InstantaneousAction("drive", t=type_truck, from=type_place, to=type_place)```. The 'from' parameter of the action is a python keyword.

**To Reproduce**
```python
from unified_planning.shortcuts import *
from unified_planning.io.pddl_writer import PDDLWriter
from unified_planning.io.python_writer import PythonWriter
from unified_planning.io.pddl_reader import PDDLReader
reader = PDDLReader()
pddl_problem = reader.parse_problem('domain.pddl', 'p01.pddl')
w = PythonWriter(pddl_problem)
w.write_problem_code_to_file('output')
```
[TPP.zip](https://github.com/aiplan4eu/unified-planning/files/8378548/TPP.zip)

**Comment by alvalentini** [comment]
This issue should be fixed in #119

**Comment by mikand** [comment]
@LBonassi95 Can you confirm the bug is gone?

**Comment by LBonassi95** [comment]
Yes, everything works. Thank you
