### ISSUE TITLE
ANML Interoperability

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#117]
### User Story
As a **Planning Expert** I want to write ANML problem formulations from the UP library to interoperate with my ANML planner. Moreover, I want to read ANML problems as UP problems.

### Acceptance Criteria

- [x] Given a UP `Problem` I can print an ANML specification (just like I can do for PDDL 2.1)
- [x] I can easily print the specification to a single file or to a python string 
- [x] Given a set of ANML files (ANML, unlike PDDL does not have a forced distinction between domain and problem) I want to read the ANML problem specification as a UP `Problem`.

### Attention Points

- ANML has several features that are currently unsupported by the UP library, we shall report clear "unsupported" errors when these are encountered.
- Several "dialects" of ANML exist, at least we should target TAMER and FAPE/ARIES dialects for the time being 
- ANML supports class-like types with actions and local fluents. In a first version it's OK to ignore these and focus on "flat" models

**Comment by vakker** [comment]
@mikand adding ANML support would be really amazing! Where is it currently on the roadmap? 
Also, FAPE is not integrated yet to UP, right?
