### ISSUE TITLE
Invalid names in the PDDL writer

### ISSUE THREAD

**Issue by Framba-Luca** [aiplan4eu/unified-planning#127]
As it is now, the PDDL writer accepts and writes in PDDL invalid PDDL name identifiers. 

The names should be checked and eventually mangled before being dumped in PDDL. (Small reminder: PDDL is case insensitive)

**Comment by mikand** [comment]
@gabi: apart from the case sensitivity, I seem to remember that you encountered other issues with the PDDL I/O. Can you list the issues here?
