### ISSUE TITLE
Action costs: limitation of the external cost-definition.

### ISSUE THREAD

**Issue by arbimo** [aiplan4eu/unified-planning#134]
In the current specification of action costs, we have an expression that is detached from the action itself but instead present in a metric field of the problem. [Definition in protobuf](https://github.com/aiplan4eu/unified-planning/blob/c806d2ba548edced7a40df7bd0e6463da4f22e15/unified_planning/grpc/unified_planning.proto#L314-L320)

This is problematic when a cost expression depends on (1) the action parameters or (2) the state in which the action is applied.
In a nutshell, doing this would require the cost expression to be scoped within the action (or at least interpreted as if it was defined within the action).

My feeling is that having action-costs defined outside of the action itself makes it very awkward when dealing with cost that are not single numeric constant for each action template. It might also complicate other processes such as grounding.

Essentially I see three options to deal with this problem:
- only allow expression that do not depend on the action's parameter / start state
- document at length how such expressions should be interpreted
- move action costs to additional field of the action

I find the first one extremely limiting and the second one quite counter-intuitive and with many possible foot-guns (especially when defining the expression in python, as one would need to keep track of the parameter objects of the action).
Thus I would favor the third one.

**Comment by madmage** [comment]
I totally agree with this: I was not completely sure to understand the reason why the action cost has been moved out from the action itself: I always saw the cost strictly connected to an action, a property of it.
I understand that there could be some corner cases where the cost of an action can be related to the problem as a whole, but I think this should be an additional possibility, not a replacement for the typical "action has a cost" view.
