### ISSUE TITLE
Allow checking for the compatibility of two types

### ISSUE THREAD

**Issue by arbimo** [aiplan4eu/unified-planning#153]
We currently have the infrastructure to check whether two types are equal. A very useful addition for type-checking planning problems is to check whether an expression has the given type, i.e., whether the type of the expression is a subset of the some other type.

This would be primarily useful in checking whether a parameter given to a fluent or to a task is compatible with the signature.

In a nutshell, it should be done by checking whether the allowed values for a type is a subset of the expected ones. In particular, the implementation should consider:
- type hierarchies
- explicit subset of numeric types. For instance, an `int[0,10]` expression can be used where an `int[0,20]` is expected but not the other way around.
- promotion of numeric types: an `int` can be used where a `real` is expected (this can be mixed with the above point).

**Digression** As a sidenote, I would add that it is slightly cumbersome to do sanity checking on the expressions as you always need to go through the `self._env....`. Would it be sensible to have an `_env` field in each `FNode` ? This would allow defining convenience methods on the `FNode` such as `.type()`, `.is_static()`, ... This would enable something like `arg.type.is_subtype(param.type)`.

**Comment by mikand** [comment]
@arbimo: we do have the `is_compatible_type` method of the type checker (https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/walkers/type_checker.py#L39)

Is this waht you had in mind.

PS: we will discuss having FNodes that know the env in a separate issue.

**Comment by mikand** [comment]
I agree that the documentation is lacking and also the signature can be improved.

@alvalentini  you created the function, yours is task to document it :smiling_imp:

**Comment by alvalentini** [comment]
I agree that we can definitely improve it. 

When I implemented it, it was just a TypeChecker's private method but I think now we can move it in the `model.types` package.

**Comment by mikand** [comment]
@alvalentini I agree, having it as a top-level function in `model.types` is a good idea

@Framba-Luca can you proceed on this?
