### ISSUE TITLE
Add transformation from plan to plan

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#161]
We currently have a transfornation between a POP plan and a sequential plan as a pair of fucntions. A more general framework shall be developed for handling different transformations (it is possible that more than one implementation for the same pair of plan kind are possible)

**Comment by Framba-Luca** [comment]
This feature is currently in the `Plan.convert_to` method.

The interface of this method is:

```python
def convert_to(self, plan_kind: PlanKind, problem: AbstractProblem) -> "Plan":
```

where the current plan (`self`)is current to the given `PlanKind`.
