### ISSUE TITLE
Default configurations based on taxonomy

### ISSUE THREAD

**Issue by roeger** [aiplan4eu/unified-planning#18]
### User Story

As a planning engine developer, I want to be able to specify default configurations to make the engine easily usable.

This story stems from the Fast Downward planning system, which has quite a large configuration space. We would like to pre-define configurations that get automatically selected based on the taxonomy and possibly more fine-grained criteria such the existence of conditional effects, quantifiers, etc.

### Acceptance Criteria

- [ ] A planning system can be integrated with a number of default configurations.
- [ ] In the integration of the planning system, one can set which configuration is used for which kind of problem.
- [ ] The mechanism is documented in the wiki.

### Additional Material

- You can have a look at the examples at http://www.fast-downward.org/PlannerUsage to get an impression of the Fast Downward configuration.

### Attention Points

- none

**Comment by mikand** [comment]
@roeger This user story should be now fully supported (I think). Feel free to reopen the issue if you think something is still missing.
