### ISSUE TITLE
DurativeAction duration based on real fluent value

### ISSUE THREAD

**Issue by AlonSpinner** [aiplan4eu/unified-planning#180]
### User Story
Hi,
I am a MSc student for robotics and am looking to incorporate your amazing repo into a multi-robot planning problem I need to solve.
In it, I would like the duration of a 'move' DurativeAction to be based on the distance between locations

```
is_connected = Fluent('is_connected', BoolType(), l_from = location, l_to = location)
distance = Fluent('distance', RealType(), l_from = location, l_to = location)

move = DurativeAction('move',  r = robot, l_from = location, l_to = location)
r = move.parameter('r')
l_from = move.parameter('l_from')
l_to = move.parameter('l_to')
move.set_fixed_duration((distance(l_from, l_to)))
move.add_condition(StartTiming(),Or(is_connected(l_from, l_to), \
                                    is_connected(l_to, l_from)))
```
### Additional Material

I Scratched my head for a good few hours, and couldn't find a way to do it.
_set_fixed_duration_ can take an FNode but the following errors rise

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cear/LocalInstalls/miniconda3/envs/maildelivery/lib/python3.9/site-packages/unified_planning/model/action.py", line 430, in set_duration_constraint
    raise UPProblemDefinitionError('Duration bound must be constant.')
unified_planning.exceptions.UPProblemDefinitionError: Duration bound must be constant.
```
Any help would be welcomed.

Thanks,
Alon

**Comment by mikand** [comment]
Hi @AlonSpinner, thanks for the report!

It looks like a bug to me. @alvalentini maybe we have a check that is too strict?

**Comment by alvalentini** [comment]
@AlonSpinner It should work now! Can you confirm it?

**Comment by AlonSpinner** [comment]
I can confirm that it works!

Thanks :)
