### ISSUE TITLE
Engine that supports Minimization Metrics

### ISSUE THREAD

**Issue by AlonSpinner** [aiplan4eu/unified-planning#188]
### User Story
Hi,
I am trying to solve a multi-robot planning problem where I would like to create an efficient plan where the robots move as less as possible but still manage to accomplish the goals.

Minimizing PLAN_LENGTH or introducing ACTION_COST via up.model.metrics should be a sound way to go, but I couldn't find an engine that supports these kinds.

### Additional

I went through all the engines offered in the AI4EU organization and found no engine that supports PLAN_LENGTH or ACTION_COST, at least not in the engine.py files. 
There also wasn't any example where a problem with a quality metric is actually solved.
The written description would suggest that enhsp should allow for such functionality, perhaps in the future.

Am I missing something?
My current solution would be to export a pddl and solver with something external.

Thanks, 
Alon

**Comment by mikand** [comment]
@AlonSpinner you are right: the current versions of fast-downward and enhsp (planners that do support optimization of either plan length or action cost) do not include these features in the supported kind.

We are working on this issue (that is related to #133), but maybe @roeger @hstairs we can already add support for ACTION_COST?

**Comment by roeger** [comment]
The Fast Downward integration (>= 0.0.3) now supports the ACTION_COST and PLAN_LENGTH metrics.

**Comment by alvalentini** [comment]
Fast Downward and ENHSP now support these metrics.
