### ISSUE TITLE
Running a planning system in a user-specified configuration

### ISSUE THREAD

**Issue by roeger** [aiplan4eu/unified-planning#19]
### User Story
As a user, I want to select a specific planning system and pass a configuration string to it to run it in a specific configuration.

This targets the expert users that run a planning engine via the UPF but do not want to use some default configuration.

### Acceptance Criteria

- [ ] Users can pick a specific planning system.
- [ ] Users can pass a configuration string (or whatever is suitable) to the planning system.
- [ ] The mechanism is documented from the user perspective.
- [ ] The mechanism is documented for the system developers who want to support this for their engine.

### Additional Material

No

### Attention Points

No

**Comment by haz** [comment]
This is one of the direct overlaps with what we're working on. Manifest files from [planutils](https://github.com/ai-planning/planutils) are going to start changing to indicate the API that should be exposed for [planning-as-a-service](https://github.com/AI-Planning/planning-as-a-service). You can see an example of the existing manifest [[here](https://github.com/AI-Planning/planutils/blob/master/planutils/packages/downward/manifest.json)], but it doesn't yet indicate what things will look like.

Generic "I am a solver" defaults, with self-defined customization for the individual planners is going to start coming by next week. Also makes sense to have some re-use mechanism (inheritance or import functionality), so that FD-specific options that are available for many configurations (lama, etc) only need to be defined once.

Anyways, this is all to say that hopefully we stay in the loop on this -- there are a few stakeholders out there just waiting for a formal configuration standard (e.g., VSCode plugin), and really don't want to see multiple versions of the same thing floating around :P.

**Comment by mikand** [comment]
@roeger @haz My interpretation of the user story is that a user of the UPF shall be able to indicate "I want an instance of FastDownward with a default configuration" or "I want an instance of FastDownward with this configuration". I have two comments:

1. For a system as FastDownward, in addition to these two queries, we could add particularly famous configuration as if they were separate planners. E.g. "I want an instance of LAMA" (If I am not mistaken you have a `--alias` option for this)
2. We might express these configuration in a manifest file shared with planutils, but the key difference is that here we want to implement these variations **by linking the FastDownward system with the UPF**, so it requires more work that simply construct the appropriate command-line for FastDownward.

As a small prototype for this, we drafted some machinery for planner selection and configuration [here](https://github.com/aiplan4eu/upf/blob/master/upf/factory.py). One can easily associate a python class inheriting from `Solver` in a custom module in the set of available solvers within the UPF. This is just a first approximation of the mechanism, but it might be flexible enough for partly supporting this user story. What is missing are custom parameters.

What do you think?

**Comment by haz** [comment]
I think you're assuming too deep of an integration. It's moreso about the ontology / planning (no pun intended) of things. In Sept, you should be able to hot-swap out the UPF integration with the new planning-as-a-service with minimal/no overhead, just by the fact that we've unified on the parameter space for defining things.

Defining a robust and comprehensive space for the API of a range of planning services is no small task. But it's one both of our projects are working towards. No (immediate) need (that I see) to actually integrate code -- just one to make sure we collectively settle on the same API space so there's uniformity across the field.

As for `--alias`'ing, yep! Definitely think that should be a default config option for FD-based systems. Not sure if there are alias-specific options, though...

**Comment by alvalentini** [comment]
In PR #12 we are working on the possibility to pick a specific planning system passing a custom configuration (Dict[str, str]).

**Comment by roeger** [comment]
@mikand For the kind of integration we have in mind, your proposal goes into the right direction. Would it make sense to already try a few things with Fast Downward to check whether it would also work "in practice" (TM)?

@haz My impression is that planutils and  the UPF target different application scenarios. We are indeed aiming at a tighter integration so I am not sure how realistic it is to just plug planutils into the UPF. The requirements from the use cases require us to think a bit beyond the usual "here is a task, give me a plan" scenario but users must be able to connect components very flexibly (involving some actual python programming).
(BTW, Fast Downward indeed has option `--alias` for a number of IPC configurations.)

**Comment by haz** [comment]
Aye, I get that. Not everything on the planutils front is through the command line, but most will be. Point isn't to nestle planutils into the engine of the UPF project. Rather, it's for us to avoid defining essentially the same ontology of capability multiple places across the field. It's about the conceptual aspect of what's done, and on the API side if UPF ever decides to jump the rung to remote webservices as a model (if this ever happens, then it only makes sense for the API to align so UPF can take advantage of whatever else is out there).

**Comment by mikand** [comment]
@roeger This user story should be now fully supported (I think). Even more so with the recent configuration space addition. Feel free to reopen the issue if you think something is still missing.
