### ISSUE TITLE
Quantification over effects in PDDL Parser

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#198]

**Comment by mikand** [comment]
Update the PDDL parser to read the quantification over effects and construct a set of effects in the UP

**Comment by roeger** [comment]
You can use the one attached to #109.

I attach another one from the citycar domain:
[problem.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/9111474/problem.pddl.txt)
[domain.pddl.txt](https://github.com/aiplan4eu/unified-planning/files/9111475/domain.pddl.txt)
