### ISSUE TITLE
Getting a planner with support for multiple operative modes

### ISSUE THREAD

**Issue by hstairs** [aiplan4eu/unified-planning#20]
### User Story
As a non-expert planning user I want to identify a planner that can be used in two operative modes: one shot plan generation and plan repair. The way I see operative modes currently implemented (i.e., through calling a factory that gives me a planner implementing only one operative mode) I cannot make this request explicitly.

As discussed, one way to support this is by calling repeatedly the factory, and then do the checking manually. It would be nice thou to have a method implementing such a functionality directly

### Acceptance Criteria

- [ ] Be able to get a planner supporting multiple operative modes
- [ ] Be informed whether there is no such a planner

**Comment by mikand** [comment]
At the moment, we only have two engines supporting more than one operative mode, namely Tamer (oneshot-planner + plan-validator) and Pyperplan (oneshot-planner + grounder). When we will have more multi-modal engines we will reconsider this issue (it should be easy enough to extend the factory for taking more tahn one OM)
