### ISSUE TITLE
Add support for Contingent Planning

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#212]
In order to add a minimal support for contingent planning in the UP we agreed with @shanigu to do the following steps:
1. Add a "SensingAction" as an InstantaneousAction with a set of observed fluents (To be decided if this needs to ba a separate class inheriting fom InstantaneousAction or not)
2. Allow a formula specifying the initial state (the semantics is that the initial state is non-deterministic). To be decided if it's OK to put this in the `Problem` class or create a separate `AbstractProblem`-derived class. 
3. Add a `ContingentPlan` as a tree structure where nodes are action instances and edges are labeled with observations (a map from observed fluents to values)

**Comment by shanigu** [comment]
1. Agreed. I suggest that it can just be an additional field in InstantaneousAction but a new child class is a reasonable alternative.
2. I suggest to split the initial state definition into a set of known fluents (identical to a classical problem), and a set of constraints over the hidden fluents, which is a set of formulas. We need to support the following operators: 
a. (oneof p1 p2 p3) - exactly one of p1 p2 p3 is true, the rest are false
b. (or p1 p2 p3) - one or more of p1 p2 p3 is true
c. (unknown p1) - either p1 is true or it is false. This is equivalent to (or p1 (not p1))
3. Note here that we should support the null observation as an edge label.

**Comment by alvalentini** [comment]
@shanigu have a look at this PR #222 and let me know if you have any feedback or suggestion.
