### ISSUE TITLE
Problem parser currently not working with temporal problems?

### ISSUE THREAD

**Issue by AfkValerik** [aiplan4eu/unified-planning#219]
I'm trying to add test cases for the temporal planning, but when i try to parse the problem with the PDDLReader it throws an exception:

`/bin/python3 /home/valerik/Desktop/programmazione/planning/planning-test-cases/up_conversion.py
Traceback (most recent call last):
  File "/home/valerik/Desktop/programmazione/planning/planning-test-cases/up_conversion.py", line 10, in <module>
    pddl_problem = reader.parse_problem((path + 'depots/depots_domain.pddl'),(path + 'depots/depots_pfile3.pddl'))
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 522, in parse_problem
    dur_act.set_fixed_duration(self._parse_exp(problem, dur_act, types_map,
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/model/action.py", line 412, in set_fixed_duration
    self.set_duration_constraint(up.model.timing.FixedDuration(value_exp))
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/model/action.py", line 401, in set_duration_constraint
    raise UPProblemDefinitionError('Duration bound must be constant.')
unified_planning.exceptions.UPProblemDefinitionError: Duration bound must be constant.`

**Comment by alvalentini** [comment]
Can you provide more details to reproduce the problem?

The problem seems to be that you are trying to parse a problem that has non-constant duration bound (as written in the error message). Non-constant duration bounds were not supported in the older versions of the library, but in the latest ones should be supported.

**Comment by AfkValerik** [comment]
Here is an example of the pddl files that threw the exception
[pddl_files.zip](https://github.com/aiplan4eu/unified-planning/files/9160026/pddl_files.zip)

**Comment by alvalentini** [comment]
Can you also provide a simple example of code that reproduce the problem and the version of the library that you are using?

**Comment by AfkValerik** [comment]
I just found out that my version was out of date, technically it showed the latest update, but visual studio wasn't updating correctly . It is actually supported now as you said, I apologize for the inconvenience.
