### ISSUE TITLE
An exercise in a MSc course on AI

### ISSUE THREAD

**Issue by asaffio** [aiplan4eu/unified-planning#22]
### User Story

1. Short story:
As a **teacher**, I want to use UPF to let my students play around with different planners.

2. Full story:
I teach an introductory course on AI in a MSc program on computer engineering.  In one of the hands-on exercises, students have to build an integrated planning and execution system to control a simulated robot.  They are given an off-the-shelf HTN planner and a low-fidelity robot simulator.  They need to write the top-level execution loop, which interacts with the planner and with the robot simulator accordingly to the following diagram.

![spa-pipeline](https://user-images.githubusercontent.com/9271258/124379875-d7a66980-dcb9-11eb-8a15-ebdf1be89991.jpg)

The robot has to transport boxes across different rooms to reach a given configuration; additional difficulties include closed doors that need to be opened, and the presence of a gremlin who occasionally displaces the boxes.

I want the students to use the UPF instead of the given planner, so they can experiment with using different planners, possibly addressing more complex tasks. 

### Acceptance Criteria

- [ ] Using the UPF should not make the exercise more complex for the students

### Additional Material

- Example of top level code that the students are expected to implement. The call to "pyhop" should be replaced by a suitable call to UPF.

<pre>
def top_level(robot, task, verbose=1):
    """ Top level execution loop: make a robot perform a task, replan on failures """
    state = State()
    while sense_plan_act(robot, state, task, verbose=verbose) is False:
        continue

def sense_plan_act(robot, state, task, onestep=False, verbose=1):
    """ Sense-Plan-Act loop: read the world state, generate a plan, execute it  """
    get_state(state, robot)
    plan = pyhop.pyhop(state, task, verbose)
    if plan:
        result = do_action(plan, robot)
        if result:
            print("Execution completed!")
        else:
            print("Execution failed!")
        return result
    else:
        print("No plan found!")
    return None
</pre>

### Attention Points

- No other relevant info for now

**Comment by mikand** [comment]
Question: currently do the students need to write the `pyhop` task themselves is it given?

**Comment by asaffio** [comment]
Students write the pyhop domain themselves, in one exercise.  Then, in a follow-up exercise  they put their planner/domain in the executor loop.

To be complete, there is also a third part where they include an ontological reasoner in the loop to do tasks like "go to the kitchen" where none of the rooms is labeled "kitchen" in the map, but we know that a kitchen must contain a stove and that there is a stove is in room-3.

**Comment by mikand** [comment]
@asaffio This user story should be now fully supported (I think). Feel free to reopen the issue if you think something is still missing.
