### ISSUE TITLE
Parsing error with nested quantifiers

### ISSUE THREAD

**Issue by stoppini** [aiplan4eu/unified-planning#239]
We noticed that in the pddl_reader the support for nested quantifiers seems broken. More precisely we tried to parse a problem involving the goal **Forall((?x)(and (at ?x) (Forall (?y) (connected ?x ?y))))**, and got a parsing error from the library as follows:

**".venv/lib/python3.10/site-packages/unified_planning/io/pddl_reader.py", line 376, in _parse_exp_
    assert act is not None
AssertionError**

The issue can be reproduced by parsing the domain and the problem attached to this issue.
[operator_test.zip](https://github.com/aiplan4eu/unified-planning/files/9611079/operator_test.zip)

**Comment by mikand** [comment]
@stoppini Thanks for the report! We'll look into this ASAP.
