### ISSUE TITLE
Truth constants as properties

### ISSUE THREAD

**Issue by alexander-sung** [aiplan4eu/unified-planning#244]
Just a minor suggestion. It seems strange to write truth constants as function calls `TRUE()` and `FALSE()`.

https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/model/expression.py#L407

How about providing them as properties of ExpressionManager? This technique is in use in UP even for more complex properties.

**Comment by arbimo** [comment]
My understanding is that FNode is mostly intended for internal usage (even though it leaks in some parts of the API).
I would say that in any public API where you would like to represent `true`, the corresponding python literal should be accepted as well. 
For instance, the `BoolenExpression` type alias (used in `And`, `Or`,...)  accepts python booleans as an alternative to more complex expressions.

**Comment by alexander-sung** [comment]
The support for the Python literals is great, no doubt. The suggestion still stands, though, since somebody decided to explicitly offer these constants. Anyway, I close this issue since it is really minor. Sometimes improvements just need the right circumstances to happen.
