### ISSUE TITLE
Parsing error for empty parameters

### ISSUE THREAD

**Issue by aymeric75** [aiplan4eu/unified-planning#245]
Hello,

Doing:

`domain = reader.parse_problem('domain.pddl', None)`

Leads to this error:

**pyparsing.exceptions.ParseException: Expected ')', found '('  (at char 1418), (line:32, col:2)**

with this domain.pddl:

(define (domain latent)
 (:requirements :strips :negative-preconditions)
 (:predicates (z0) (z1) (z2) (z3) (z4) (z5) (z6) (z7) (z8) (z9) (z10)
  (z11) (z12) (z13) (z14) (z15) (z16) (z17) (z18) (z19) (z20) (z21)
  (z22) (z23) (z24) (z25) (z26) (z27) (z28) (z29) (z30) (z31) (z32)
  (z33) (z34) (z35) (z36) (z37) (z38) (z39) (z40) (z41) (z42) (z43)
  (z44) (z45) (z46) (z47) (z48) (z49))
 (:action a3 :parameters () :precondition
  (and (z0) (z3) (z5) (not (z9)) (not (z10)) (not (z12)) (not (z24))
       (not (z30)) (z34) (z37) (not (z42)))
  :effect
  (and (z0) (not (z3)) (not (z5)) (z9) (z10) (z12) (z24) (z30)
       (not (z34)) (not (z37)) (z42)))
 (:action a11 :parameters () :precondition
  (and (z0) (not (z3)) (not (z8)) (not (z9)) (z21) (not (z24)) (z25)
       (z35) (z39))
  :effect
  (and (z0) (not (z3)) (z8) (z9) (not (z21)) (not (z24)) (not (z25))
       (not (z35)) (not (z39))))
 (:action a13 :parameters () :precondition
  (and (z0) (not (z2)) (not (z3)) (z9) (z12) (not (z21)) (z24)
       (not (z25)) (z31) (z32) (not (z37)))
  :effect
  (and (z0) (z2) (not (z3)) (not (z9)) (not (z12)) (z21) (not (z24))
       (z25) (not (z31)) (z32)))
 (:action a22 :parameters () :precondition
  (and (not (z0)) (not (z3)) (not (z9)) (z15) (not (z17)) (z19)
       (not (z20)) (not (z24)) (z46))
  :effect
  (and (not (z0)) (z3) (z9) (not (z15)) (z17) (not (z19)) (not (z20))
       (not (z24)) (not (z46))))
 (:action a29+9 :parameters () :precondition
  (and (z0) (z3) (z5) (not (z9)) (not (z10)) (not (z11)) (not (z12))
       (not (z15)) (not (z16)) (not (z24)) (z27) (not (z31)) (z41))
  :effect
  (and (z0) (not (z3)) (not (z5)) (z9) (z10) (z11) (z12) (z15) (z16)
       (z24) (not (z27)) (z31) (not (z41)))))

Best regards

Aymeric

**Comment by mikand** [comment]
@aymeric75 Just a guess from a first look: have you tried renaming the action `a29+9`? I think our parsed does not allow `+` or other special symbols in action/fluents/parameter names...

**Comment by aymeric75** [comment]
@mikand Hello, I just replaced + by plus and - by minus, but still the same error. thanks

**Comment by mikand** [comment]
@Framba-Luca Can you have a quick look?

**Comment by Framba-Luca** [comment]
Hi @aymeric75 , I tried to parse the given file and I get the same error.

But then i changed `a29+9` with `a29plus9` and it works fine for me. The problem is that the `+` is not a valid character for identifiers in PDDL (like the action name).

Let me know if this solves your issue

**Comment by aymeric75** [comment]
Yep, it's working, thanks
