### ISSUE TITLE
How to remove preconditions that are already present in the effect ? (or vice versa)

### ISSUE THREAD

**Issue by aymeric75** [aiplan4eu/unified-planning#252]
Hello,

I have been through the [documentation ](https://unified-planning.readthedocs.io) and through the __unified_planning.model.problem.Problem_ class_ but I don't think this feature exists.

What I want to do,  it's to remove unnecessary duplicates between preconditions and effects of the actions, this is very useful to obtain results (in term of invariants) from some tools,  like Fast Downward.

For instance, in action _a0_ (see _domain.pddl_ attached) _z15_ is at the same time in the precondition **and** in the effect, I would like to remove it from effect.

My code for now :
```

from unified_planning.io import PDDLReader, PDDLWriter

def main():

	reader = PDDLReader()
	domain = reader.parse_problem('domain.pddl', None)

	for a in domain.actions:

		for pre in a.preconditions[0]._content[1]:
			for eff in a.effects:
				# if same variable
				if(str(eff._fluent) in str(pre)):
					duplicate = False
					# if both are False
					if ( "(" in str(pre) and not eff._value ):
						duplicate = True
					# if both are True
					if ( "(" not in str(pre) and eff._value ):
						duplicate = True
					# remove form the Effects
					if(duplicate):
						a.effects.remove(eff)

if __name__ == "__main__":
	main()

```

Thank you

Aymeric

**Comment by alvalentini** [comment]
Hi @aymeric75, 
you are right, we do not have the code to automatically do that.

I can give you some advices:
- as a general comment, do not use private attributes (e.g. `_content`);
- the problem with your code is that you are not guaranteed that the variable you called `pre` is a literal, since in the preconditions you can have any expressions. You can use this [walker](https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/model/walkers/dnf.py) to convert the expression in DNF, I think it could be useful for what you are doing;
- to update the list of effects you should call the `clear_effects` method and then re-add the needed effects.

Am I answer your question?

**Comment by aymeric75** [comment]
Hello @alvalentini  thanks for your answer, but...

`- as a general comment, do not use private attributes (e.g. _content);`
Ok, but I don't see what could I use

`- the problem with your code`
I am sure that in the preconditions only literal appears (this is the way the PDDL are formatted in my problem), so this is not a problem

I have a last question though, how can I remove an element from the tuple of preconditions ?
I.e. how can I remove an element from  **a.preconditions[0]._content[1]** ? If you know, it would help me a lot :)

Cheers

**Comment by aymeric75** [comment]
Well, my code above actually does not return what I expected. Any "clean" solution (i.e. without comparing strings) is still welcome...

**Comment by alvalentini** [comment]
You can take a look at the methods of this [class](https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/model/fnode.py#L28).

If you are in the fragment of classical planning and you are sure that `a.preconditions[0]` is an `and` of literals, you can update your code with something like:
```
from unified_planning.shortcuts import *

assert len(a.preconditions) == 1
assert a.preconditions[0].is_and()

effects = a.effects
a.clear_effects()
to_keep = []
for eff in effects:
    if eff.value.is_true():
        c = eff.fluent
    elif eff.value.is_false():
        c = Not(eff.fluent)
    else:
        assert

    if c not in a.preconditions[0].args:
        to_keep.append(eff)

for eff in to_keep:
    a.add_effect(eff.fluent, eff.value, eff.condition)

```

**Comment by alvalentini** [comment]
@aymeric75 can we close this issue?

**Comment by aymeric75** [comment]
yes thanks
