### ISSUE TITLE
Allow PDDLParser to parse strings directly

### ISSUE THREAD

**Issue by shanigu** [aiplan4eu/unified-planning#262]
It would be good to have PDDLReader take not only file names, but also the PDDL string directly and pass it.
Something like: 
reader=PDDLReader()
problem=reader.parse_problem_string(domain_string,problem_string)

This would make calling one planner from another easier, at least for us at the CPOR branch.

**Comment by mikand** [comment]
It's a good idea. @Framba-Luca it should be fairly easy, can you do that?
