### ISSUE TITLE
ENHSP Seems to Not Work

### ISSUE THREAD

**Issue by Yomaster10** [aiplan4eu/unified-planning#275]
**Describe the bug**
Every time I try to run the ENHSP planner on any problem for which it should be a valid solver, it only ever returns that it couldn't find any plan (even when other plans like Fast Downward were indeed able to solve the problem).

**To Reproduce**
Try to solve any classical planning problem with ENHSP. 

**Expected behavior**
I would expect to receive a valid plan.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by hstairs** [comment]
Hi Yomaster10! What version of ENHSP and UP are you using? It could be that you don't have the right version of java installed on your machine (>=17), but that should have been raised as an error at installation time. Anyway, as @mikand said, if you provide us with a piece of code, we can have a better understanding of your situation!

**Comment by Framba-Luca** [comment]
@Yomaster10 I am closing this as it seems resolved. If it is not, just let me know!
