### ISSUE TITLE
PartialOrder plan's replace_action_instances() method not working correctly

### ISSUE THREAD

**Issue by bPat429** [aiplan4eu/unified-planning#279]
I've found that PartialOrder plan's replace_action_instances() method doesn't work as expected, linking existing ActionInstances as successors to the current action graph node. Instead a new ActionInstance is created as the successor which means the structure of the graph is lost when translated to ActionInstances.

At the end is a function that works for my purposes. I hope this helps!

**To Reproduce**
Try to use replace_action_instances() on a plan to un-ground the action instances:
//'plan' is a PartialOrderPlan object
resplan = plan.replace_action_instances(
    plan, grounding_result.map_back_action_instance
)
//Then print the resplan, and compare to the original plan

**Expected behavior**
The method iterates over all nodes in the graph, replacing them with corresponding ActionInstance objects. The method also iterates over all successor nodes, per graph node and replaces with the corresponding existing ActionInstance object.

**Desktop (please complete the following information):**
 - OS: AlmaLinux 9.1 (Lime Lynx)

Still an issue as of 02/12/2022 (I checked the github source code https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/plans/partial_order_plan.py)

**Additional context**
I've implemented a fix that works for my purposes. n.b. this is a function outside of the PartialOrderPlan class for my own convenience.
  ```
def fixed_replace_action_instances(
      plan,
      replace_function: Callable[
          ["plans.plan.ActionInstance"], Optional["plans.plan.ActionInstance"]
      ],
  ) -> "plans.plan.Plan":
      """
      Custom function for replacing action instances of a partial_order_plan
      The original function has two errors. First for plans of length 1 with no successors the plan is discarded.
      Second the successors are duplicated.
      Returns a new `PartialOrderPlan` where every `ActionInstance` of the current plan is replaced using the given `replace_function`.
  
      :param replace_function: The function that applied to an `ActionInstance A` returns the `ActionInstance B`; `B`
          replaces `A` in the resulting `Plan`.
      :return: The `PartialOrderPlan` where every `ActionInstance` is replaced using the given `replace_function`.
      """
      new_adj_list: Dict[
          "plans.plan.ActionInstance", List["plans.plan.ActionInstance"]
      ] = {}
      # The approach used is to generate equivalent keys for all nodes first, then add successors later.
      # This is done because successors need to map exactly to the corresponding node object, and so
      # the replace_function can only be called once per unique object.
  
      new_key_dict = {}
      # First add all replaced nodes as keys, but leave successors for later
      for node in plan._graph.nodes:
          key = replace_function(node)
          if key is not None:
              new_key_dict[node] = key
      # Populate the new adjacency dictionary with the replaced action instances
      # It is easier to match instances using the adjacency dict
      for node in plan._graph.nodes:
          if node in new_key_dict:
              key = new_key_dict[node]
              replaced_neighbors = []
              for successor in plan._graph.neighbors(node):
                  if successor in new_key_dict:
                      replaced_neighbors.append(new_key_dict[successor])
              if len(replaced_neighbors) > 0:
                  new_adj_list[key] = replaced_neighbors
              # This is the only functional change to this part of the code. Without this
              # else plans of length 1 are lost
              else:
                  new_adj_list[key] = []
      new_env = plan._environment
      for ai in new_adj_list.keys():
          new_env = ai.action.env
          break
      return up.plans.PartialOrderPlan(new_adj_list, new_env)
```

**Comment by mikand** [comment]
@Framba-Luca can you please have a look?

**Comment by bPat429** [comment]
My understanding of how PartialOrderPlans works may be wrong, so just to clarify:

My understanding of PartialOrderPlans is:

Start with a network of nodes. Each node corresponds to an action. The position of the node on the network denotes the position in the partial order plan.
ActionInstances are representations of a specific action executed at a specific point in the plan. If two ActionInstances have the same action, but are not the same object then they represent that action at different points in the plan.

By creating a whole new ActionInstance for a node's successor nodes this separates the true successor action from the current node.
So:
Let the set of actions {a, b, c}
all have a successor action {d}
and {d} has successor actions {e, f, g}

As is the replace_action_instances() method will turn this into:
{a1, b1, c1} have successor {d1}
{d1} has no successors
{d2} has successors {e1, f1, g1}

**Comment by Framba-Luca** [comment]
@bPat429 I think you are totally right!
When I coded this, I didn't think about the fact that 2 calls to the replace function with the same `ActionInstance` would create 2 different `ActionInstances`. 

Could you share with me the code you used to find this error?

**Comment by bPat429** [comment]
Happy to help!

My code is at:
https://gitlab.com/BPat123/up-smt-engine/
And the function is called on line 105 in:
https://gitlab.com/BPat123/up-smt-engine/-/blob/main/up_SMT_engine/SMTPlanner.py

I'm misusing PartialOrderPlans because I wanted a way to preserve sets of parallel actions in a plan so my code is probably quite confusing, sorry!
