### ISSUE TITLE
Classical planners do not accept negation as preconditions

### ISSUE THREAD

**Issue by shanigu** [aiplan4eu/unified-planning#288]
**Describe the bug**
Pyperplan and Tamer do not accept negative preconditions. While I know that this is the standard in classical planning, it is undesirable. It is natural to specify negative preconditions in many cases. If we want UP to be used by people, we should not have such restrictions.

Obviously, one can compile negative preconditions out, but this compilation should be done within the planner, if need be. 

As a side note, using negative preconditions is a requirement for CPOR, so this is blocking me currently.

**Comment by mikand** [comment]
@shanigu Tamer should support negative preconditions, while pyperplan does not. Do you have examples where Tamer complains about negative preconditions?

We have a compiler to remove them, but it should be invoked manually if needed. Have a look here in the "Negative precondition Remover" section: https://github.com/aiplan4eu/unified-planning/blob/master/notebooks/Compilers_example.ipynb
