### ISSUE TITLE
Pypi installation experience improvement

### ISSUE THREAD

**Issue by racinmat** [aiplan4eu/unified-planning#292]
### User Story
As an average programmer I want to easily install this library, see the link to pypi in github, example how to install it from pypi and see all the needed information in the pypi site.

I was able to find https://pypi.org/project/unified-planning/ but it is nowhere linked with the repo in a transparent manner, they should be linking each other so people could verify the pypi package actually comes from this repository.

### Acceptance Criteria

- [ ] There is badge or link pointing to pypi
- [ ] There is a line of code showing how it can be installed using `pip`

**Comment by alvalentini** [comment]
@racinmat thanks for the suggestions.

Now we have a badge in the README pointing to pypi and we have a PR that aims to improve the documentation, including installation instructions.
