### ISSUE TITLE
Can't use FINAL_VALUE with latest unified-planning.

### ISSUE THREAD

**Issue by racinmat** [aiplan4eu/unified-planning#296]
**Describe the bug**
Currently I am not able to install any planner that is able to optimize for final value.
The latest unified-planning, 0.4.2, support only up-enhsp 0.0.5 https://github.com/aiplan4eu/unified-planning/blob/v0.4.2/setup.py#L36 which does not yet support final value, and does not allow installation of newer versions which support it. 
I was not able to find which other solver would support it.

**Comment by alvalentini** [comment]
@racinmat thanks for the bug report.

In the last release, this issue should be solved.

Can you check and, if solved, close the issue?

**Comment by racinmat** [comment]
Now it shows it supports the final value, thanks.
