### ISSUE TITLE
SequentialSimulator cannot be used with problems that have QualityMetrics

### ISSUE THREAD

**Issue by sebastianstock** [aiplan4eu/unified-planning#302]
I would like to use the `SequentialSimulator` for  monitoring a plan for a problem that has a QualityMetric assigned.
However, creating the `SequentialSimulator` for such a problem raises a `UPUsageError`:
> unified_planning.exceptions.UPUsageError: We cannot establish whether sequential_simulator is able to handle this problem

This happens because of the check in the constructor of the `SimulatorMixin` if the problem_kind is supported. Currently, `SequentialSimulator` does not support any QualityMetric. 

If I avoid that UPUsageError with `SequentialSimulator(self._problem, error_on_failed_checks=False)` I get an `AssertionError` from the `Grounder`  in line 65 of `sequential_simulator.py`: `assert Grounder.supports(pk)`

It works if I remove the quality metric from the problem after generating the plan and before use the simulator. But this feels a bit hacky.
Therefore, I wanted to ask if this is the intended behavior or if we could instead avoid the checks for the support of quality metrics in the simualtor?

**Comment by mikand** [comment]
I think this raises an interesting question: should a `Simulator` accept a problem with quality metrics or not? I think we shall document that such problems are supported, but quality metrics are simply ignored (or at most just evaluated)

**Comment by roeger** [comment]
I vote for accepting problems with metric. Currently, this limitation also carries over to the 'SequentialPlanValidator'. In my test cases, I hence clone the problem, remove the metric and validate the plan on this modified problem. Feels unnecessary.
