### ISSUE TITLE
Handle name unicty in a Problem

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#315]
In UP we have the following named entities, we need to understand which (if any) could share the name with which other.
- Fluent
- *Action
- Task
- UserType
- Parameter
- Variable
- Object
- Agent

**Comment by mikand** [comment]
Proposal.

For me, except for `Parameter`'s, the naming should be unique in the scope of a `Problem`. 
Parameters names could be reusedbetween different `Fluent`'s and `Action`'s, but need to be unique for an `Action` or `Fluent`.

**Comment by mikand** [comment]
@alvalentini @Framba-Luca Any comment here?

**Comment by mikand** [comment]
After some discussion with @alvalentini we decided the following.

- By default, the UP will raise an exception when names are re-used between Fluents, *Actions, Tasks, UserTypes, Objects and Agents
- It will be possible to set a flag in the environment to change this error in a warning stating that, depending on the engine, the constructed problem might or not work properly.

under any circumstance, it will be impossible to create two entities of the same type in the same scope (e.g. two actions with the same name or two parameters of he same action with the same name)

**Comment by Framba-Luca** [comment]
Here is a table with the naming conflicts and the solution proposed: 
| Conflicting names | Action | Fluents | UserType | Object | Tasks | Method | Agent | Agent.Action | Agent.Fluent |
|-------------------|--------|--------:|----------|--------|-------|--------|-------|--------------|--------------|
| Action            | 1      | 2       | 2        | 2      | 2     | 2      | 3     | 3            | 3            |
| Fluents           |        | 1       | 2        | 2      | 2     | 2      | 3     | 3            | 3            |
| UserType          |        |         | 1        | 2      | 2     | 2      | 2     | 2*           | 2*           |
| Object            |        |         |          | 1      | 2     | 2      | 2     | 2*           | 2*           |
| Task              |        |         |          |        | 1     | 2      | 3     | 3            | 3            |
| Method            |        |         |          |        |       | 1      | 3     | 3            | 3            |
| Agent             |        |         |          |        |       |        | 1     | 2*           | 2*           |
| Agent.Action      |        |         |          |        |       |        |       | 4            | 5            |
| Agent.Fluent      |        |         |          |        |       |        |       |              | 4            |

LEGENDA:
\* Feature still has to be implemented.
1 Always raises an `Exception`.
2 Raises an `Exception` or a `warning`, based on the flag `error_used_name` in the `Environment`.
3 Can't be found in the same `Problem`. 
4 Always raises an `Exception`, but only if in the same `Agent`; different `Agents` don't interfere one another with `Actions` names or `Fluent` names.
5 Raises an `Exception` or a `warning`, based on the flag `error_used_name` in the `Environment`, but only if the `Action` and the `Fluent` are in the same `Agent`.

**Comment by mikand** [comment]
@iocchi @fabio-patrizi Do you have any feedback on the multi-agent part?

**Comment by fabio-patrizi** [comment]
Hi all, as to the MA part, the proposal seems perfectly reasonable to me.
