### ISSUE TITLE
Conflicting identical action effects in SequentialSimulator

### ISSUE THREAD

**Issue by philher** [aiplan4eu/unified-planning#316]
**Describe the bug**
Using the sequential simulator, when an action instance ends with two identical effects assignment after grounding, the corresponding event is considered as not applicable.

For example, when considering a possible plan resulting from the hierarchical domain _Factories-simple_ (available [here](https://github.com/panda-planner-dev/ipc2020-domains/blob/master/total-order/Factories-simple/domain.hddl)), it is possible to obtain an instantiation of the `fuse` action as `fuse(resource_f2_0, resource_0, resource_0, location_1)` (detailed below). 
The effects of this instantiation are clearly compatible even though we have two assignment to the same fluent `resource-at resource_0 location_1`, as they assign it the same value twice.

<details>
  <summary>Lifted action</summary>

```pddl
 (:action fuse
        :parameters (?r ?r1 ?r2 - resource ?l - location)
        :precondition (and
            (fuses ?r ?r1 ?r2)
            (resource-at ?r1 ?l)
            (resource-at ?r2 ?l)
        )
        :effect (and
            (not (resource-at ?r1 ?l))
            (not (resource-at ?r2 ?l))
            (resource-at ?r ?l)
        )
    )
```
</details>

<details>
  <summary>Ground action</summary>

```text
action: fuse(resource_f2_0 resource_0 resource_0 location_1)
    preconditions: (and
            (fuses resource_f2_0 resource_0 resource_0)
            (resource-at resource_0 location_1)
            (resource-at resource_0 location_1)
        )
    effects:  (and
            (not (resource-at resource_0 location_1))
            (not (resource-at resource_0 location_1))
            (resource-at resource_f2_0 location_1)
        )
```
</details>

**To Reproduce**
I cannot give a clear set of data to reproduce it, as it depends on its integration in a larger script.

**Expected behavior**
Expected the action described earlier to not have conflicting effects.

**Additional context**
I've tried doing a quick & dirty fix for my own use https://github.com/philher/unified-planning-custom/commit/d6372edea9787e61a1d299646e64fd47bf32c702.
It appears to work, but I have not checked it for side effects at all, however it may be useful to pinpoint the source of the error.

**Comment by arbimo** [comment]
@mikand This is probably best handled with #305 : essentially in the classical semantics `S' = (S \ { del }) UNION {add}`, identical effects are grouped together and thus not seen as incompatible.

**Comment by mikand** [comment]
@Framba-Luca please check. This should be now fixed in master.
