### ISSUE TITLE
Forall quantification over effects

### ISSUE THREAD

**Issue by Framba-Luca** [aiplan4eu/unified-planning#405]
Here are the steps to support the Forall quantification over the effects in the UP.

Basic support:
- [x] Add a field to the `up.model.effect.Effect` class that contains a sequence of `up.model.variable.Variable`; those variables can be used in the other fields of the effect. (Small note, the Effect class is immutable)
- [x] Add the feature to the `up.model.problem_kind` that flags when a problem has a Forall quantification over the effects.
- [x] Modify the `up.model.problem.Problem.kind` method to set the above flag when the problem has quantified effects; this not only for `Problem`, but for all the different types of problem supported.
- [x] In all the `add_effect` methods (e.g. add_timed_effect, add_increase etc.) add the parameter to add the sequence of `Variables`.

Advanced support:
- [x] All the specified variables that are not actually used in the effect are not stored. (Suggestion: Use free_vars_oracle in the environment for this)
- [x] The `up.engines.compilers.quantifiers_remover` removes the `Forall` effects by adding the equivalent grounding.
- [x] Add the support in the `PDDLWriter`.
- [x] Now the `PDDLReader` does the grounding while parsing; it can be avoided and it can create `Forall` effects in the UP. (The code removed here can be used as a guideline for the `QuantifiersRemover`)
- [x] Add the support to `ANMLWriter`.
- [x] Add the support to `ANMLReader`.

**Comment by Framba-Luca** [comment]
Should you have any issue or need clarifications, I am available to give you support.

**Comment by sebastianstock** [comment]
> Should you have any issue or need clarifications, I am available to give you support.

Thank you! :-)
