### ISSUE TITLE
Exception on example notebooks.

### ISSUE THREAD

**Issue by muzoaydo** [aiplan4eu/unified-planning#409]
### Problem
When i run the 02-optimal-planning.ipynb notebook example, on 7'th section where assert functions are written, i get this error:

```---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[c:\Users\muzo1\Desktop\UPF\unified-planning\docs\notebooks\02-optimal-planning.ipynb](file:///C:/Users/muzo1/Desktop/UPF/unified-planning/docs/notebooks/02-optimal-planning.ipynb) Cell 19 in 
----> [1](vscode-notebook-cell:/c%3A/Users/muzo1/Desktop/UPF/unified-planning/docs/notebooks/02-optimal-planning.ipynb#X24sZmlsZQ%3D%3D?line=0) assert final_report.status == PlanGenerationResultStatus.SOLVED_OPTIMALLY
      [2](vscode-notebook-cell:/c%3A/Users/muzo1/Desktop/UPF/unified-planning/docs/notebooks/02-optimal-planning.ipynb#X24sZmlsZQ%3D%3D?line=1) assert plan == expected_plan

AssertionError:
```

**To Reproduce**
1. Go to '02-optimal-planning.ipynb'
2. Click on 'Run All'
3. Scroll down to '7'th section'

Same error raises at 10'th section as well.

**Expected behavior**
I believe it should have solve the problem optimally and not raise an exception.

**Screenshots**
![image](https://github.com/aiplan4eu/unified-planning/assets/64156908/77d22236-04a8-4dcd-aaf4-907b0983afdc)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - IDE: VS Code

**Comment by alvalentini** [comment]
We currently have a limitation that prevents using some planners (fast-downward, enhsp, lpg) through notebooks in windows.

**Comment by muzoaydo** [comment]
Is there any way i work around this issue ? Since we are going to develop our AIPlan4EU project with optimal planning, we can't move forward atm.

**Comment by alvalentini** [comment]
You can convert a python notebook into a normal python file and then it should work fine.

**Comment by muzoaydo** [comment]
Thank you.
