### ISSUE TITLE
'Error unknown predicate and used in precondition of action'

### ISSUE THREAD

**Issue by aymeric75** [aiplan4eu/unified-planning#421]
**Describe the bug**
when I run `pyperplan domainWithoutNeg.pddl problemWithoutNeg.pddl` (from cmd line), I get

`'Error unknown predicate and used in precondition of action'`

The problem comes from how the domainWithoutNeg.pddl was created (by unified-planning code)

[problem.txt](https://github.com/aiplan4eu/unified-planning/files/11622819/problem.txt)

**To Reproduce**
Here is the code that produces the domainWithoutNeg.pddl and problemWithoutNeg.pddl
```

import unified_planning
from unified_planning.shortcuts import *
from unified_planning.io import PDDLReader, PDDLWriter


reader = PDDLReader()
pddl_problem = reader.parse_problem('./domain.pddl', './problem.pddl')
print(pddl_problem)

# Get the compiler from the factory

dcr_kind = pddl_problem.kind

dcr_problem = pddl_problem


# create a version of the "problem" without negative preconditions
with Compiler(
        problem_kind = dcr_kind,
        compilation_kind = CompilationKind.NEGATIVE_CONDITIONS_REMOVING
    ) as negative_conditions_remover:

    # After we have the compiler, we get the compilation result
    ncr_result = negative_conditions_remover.compile(
        dcr_problem,
        CompilationKind.NEGATIVE_CONDITIONS_REMOVING
    )
    ncr_problem = ncr_result.problem
    ncr_kind = ncr_problem.kind

    #assert not ncr_kind.has_negative_conditions()


    w = PDDLWriter(ncr_problem)


    w.write_domain('./domainWithoutNeg.pddl')
    w.write_problem('./problemWithoutNeg.pddl')


```

See attached the original file (domain.pddl and problem.pddl) and the resulting files ([domainWithoutNeg.txt](https://github.com/aiplan4eu/unified-planning/files/11622802/domainWithoutNeg.txt).pddl and problemWithoutNeg.pddl)
[problemWithoutNeg.txt](https://github.com/aiplan4eu/unified-planning/files/11622805/problemWithoutNeg.txt)
[domain.txt](https://github.com/aiplan4eu/unified-planning/files/11622813/domain.txt)
[problem.txt](https://github.com/aiplan4eu/unified-planning/files/11622816/problem.txt)

**Comment by Framba-Luca** [comment]
Hi @aymeric75 , this should be fixed in the current version of master.

**Comment by Framba-Luca** [comment]
Hi @aymeric75 , let me know if you still have this issue or it can be closed.
