### ISSUE TITLE
Problems with precondition

### ISSUE THREAD

**Issue by antoniojbm** [aiplan4eu/unified-planning#450]
Good afternoon I am trying to add a negative precondition. Looking in the documentation I find that it would be like this:
`
add_precondition(Not(hadVessel(d)))`

But when I try to execute I get this error:

```
in _convert_action
    raise UPUnsupportedProblemTypeError(f'In precondition: {x} of action: {action} is not an AND or a FLUENT')
unified_planning.exceptions.UPUnsupportedProblemTypeError: In precondition: (not hadVessel(d)) of action: action vessel_go_to_deltaAnch(Vessel v, WaitingP wv, DeltaAnch d) 


```

**Comment by Framba-Luca** [comment]
Hi @antoniojbm , could you also send an example of the code that is not working? It would really help!

**Comment by Framba-Luca** [comment]
@antoniojbm from your error it seems you are using pyperplan with negative preconditions. 

Pyperplan does not support negative preconditions. Consider using a compiler (with` CompilationKind = NEGATIVE_CONDITIONS_REMOVING`) or use another planner (suggested option).

**Comment by Framba-Luca** [comment]
Hi @antoniojbm , can this issue be closed or it is still a problem?

**Comment by mikand** [comment]
@antoniojbm Closing the issue. Feel free to reopen if Luca's answers are not what you were looking for.
