### ISSUE TITLE
Issue with validating a plan generated by not integrated planner

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#451]
**Describe the bug**

I generated a plan through a planner that is not supported by unified planning and then ported the actions of the plan using the following code:
```

reader = PDDLReader()
task = reader.parse_problem('domain.pddl', 'problem.pddl")

with Compiler(problem_kind=self.task.kind, compilation_kind=CompilationKind.GROUNDING) as grounder:
            ground_problem = grounder.compile(self.task, compilation_kind=CompilationKind.GROUNDING).problem

# used some external planner defined in the dict call model.

plan = []
## linearize partial-order plan
for step in range(self.encoder.horizon):
    for action in self.encoder.ground_problem.actions:
        if is_true(model[self.encoder.action_variables[step][action.name]]):
            plan.append(ActionInstance(action))
ufplan = SequentialPlan(plan, ground_problem)
```

After converting the extracted plan, I used:
```
with PlanValidator(problem_kind=task.kind, plan_kind= ufplan) as validator:
    if validator.validate(task, ufplan):
        print('The plan is valid')
    else:
        print('The plan is invalid')
```

I get an error saying that some action does not belong to the problem.

**Expected behavior**
I should receive a plan that is valid or not.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safari
 - Version 16.3

**Comment by Framba-Luca** [comment]
Hi @MFaisalZaki , there are 2 problems with your code:
1) the SequentialPlan second argument is the environment, so you should pass task.environment (or ignore it, the default should be OK)
2) you are creating a plan for the grounded problem and you are validating it for the original problem (task).

So, you either validate it for the grounded problem, or convert every ActionInstance of the plan into the equivalent action of the original problem.

How to do this? It is explained in the section 5.9 of the [notebook on compilers](https://unified-planning.readthedocs.io/en/latest/notebooks/05-compilers.html) 

Let me know if you still have issues.

**Comment by MFaisalZaki** [comment]
Hi @Framba-Luca,

Thanks for your reply. I have updated the plan validator to use the grounded task and I get this error:
![Screenshot from 2023-07-12 09-39-53](https://github.com/aiplan4eu/unified-planning/assets/9129265/c7eed36f-1268-4d4f-8354-d734d276d9fd)

Here is the updated code:
```
with PlanValidator(problem_kind=task.kind, plan_kind= ufplan) as validator:
    if validator.validate(ground_problem, ufplan):
        print('The plan is valid')
    else:
        print('The plan is invalid')
```

**Comment by Framba-Luca** [comment]
Here are the modifications you need in your code (with a comment explaining why):

```
with PlanValidator(
     problem_kind=ground_problem.kind, # You are getting a validator for the ground problem
     plan_kind= ufplan.kind, # You need to pass the kind of the plan, not the whole plan
) as validator:
    if validator.validate(ground_problem, ufplan):
        print('The plan is valid')
    else:
        print('The plan is invalid')
```

**Comment by MFaisalZaki** [comment]
It works now. Thanks for your guidance, @Framba-Luca.
