### ISSUE TITLE
OptimalityGuarantee not working.

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#460]
I'm trying to get optimal plans using the `enhsp` planner. However, setting the `optimality_guarantee=True` or `optimality_guarantee=OptimalityGuarantee.SOLVED_OPTIMALLY` does not work. Here is the code sample I'm using besides the [planning problem](https://github.com/aiplan4eu/unified-planning/files/12123081/files.zip).

```
from unified_planning.io import PDDLReader
from unified_planning.shortcuts import *

planning_task = PDDLReader().parse_problem('domain.pddl', 'prob1.pddl')
with OneshotPlanner(name='enhsp', optimality_guarantee=True) as planner:
        result = planner.solve(task)
        horizon = len(result.plan.actions)
assert(horizon == 10)
```

The optimal plan length should be 10, but the generated plan is 12.

I have checked the [configuration](https://sites.google.com/view/enhsp/home/how-to-use-it) of the `enhsp`, and we can use the `-planner opt-hmax` to generate optimal plans. However, I cannot pass such a configuration to the planner using the `params` provided by the `OneshotPlanner`. I have tried `["-planner", "opt-hmax"]` and `{"planner": "opt-hmax"}`, but I receive thrown errors.

**Comment by alvalentini** [comment]
To select an optimal planner you can do as follow:
```python
with OneshotPlanner(problem_kind=planning_task.kind, 
                    optimality_guarantee=OptimalityGuarantee.SOLVED_OPTIMALLY) as planner:
```

or if you want to use a enhsp in its optimal configuration:
```python
with OneshotPlanner(name='enhsp-opt') as planner:
```

**Comment by MFaisalZaki** [comment]
Thanks for highlighting that.
