### ISSUE TITLE
PDDLWriter does not correctly create HDDL files

### ISSUE THREAD

**Issue by baumfalk** [aiplan4eu/unified-planning#506]
According to https://unified-planning.readthedocs.io/en/latest/interoperability.html#pddl-mapddl-hddl-reader-and-writer, the PDDLWriter class should be able to write a HDDL problem to disk. 

However, when I try to write a simple HDDL problem to disk (or even print it using the get_domain and get_problem method of the PDDLWriter class), the methods and tasks are not written to file (since there exists no code for it do to so).

**Comment by mikand** [comment]
@arbimo Maybe you can help here?

**Comment by arbimo** [comment]
Indeed it is a known limitation of the  PDDL writer to not support the hierarchical part of the domain.
It should be fairly straightforward to add it since all the building blocks are there for PDDL already.

So in this case, the documentation is wrong.

**Comment by arbimo** [comment]
If anyone reads this with interest in an export to HDDL: I would be happy to review a PR adding support extending the `PDDLWriter` to support HDDL. It should be fairly straightforward even for someone who never touched the internals of the library.
