### ISSUE TITLE
Write PDDL with Timed Initial Literals

### ISSUE THREAD

**Issue by karpase** [aiplan4eu/unified-planning#525]
### User Story
As a **[USER]** I want write PDDL files for a problem which includes timed initial literals, in order to call a PDDL-based planner to solve it.

Line 380 of pddl_writer.py raises an exception saying "PDDL2.1 does not support timed effects or timed goals.", which is true - but we can also write PDDL 2.2 (or 3.1).

The PDDL reader can read timed initial literals, so I suspect this line may be there to handle more complex cases, but I'm not sure.

### Acceptance Criteria

- [ ] Create a problem with timed initial literals, successfully write it to a PDDL file using PDDLWriter.

**Comment by alvalentini** [comment]
@karpase this issue has been fixed in #543. 

I close this issue, but feel free to reopen it if needed!
