### ISSUE TITLE
Problem loading classical planning instances with action cost 

### ISSUE THREAD

**Issue by alvaro-torralba** [aiplan4eu/unified-planning#526]
**Describe the bug**
The library is too restrictive by requiring all fluents to be declared in the initial state. This causes the library not to work with exsiting benchmarks: the transport domain used in IPC'08, 11 and 14, for example.  
My use case only involves loading the domain and problem file and solving them with a planner (I'm using fast downward). I include a minimal script below.

The reason is that there is a fluent (road-length ?l1 ?l2 - location) that indicates the length of the road between two locations. This is used as the cost of the action drive. However, there is also a predicate (road ?l1 ?l2 - location) that specifies that there is a road between the two locations. So, the problem file does not specify the length of roads that do not exist.

Currently, the library complains that all values should be defined: Initial value not set for fluent: road-length(city-1-loc-1, city-1-loc-1)
However, having to enumerate all values would be cumbersome and may significantly increase the size of the instances. 

So, it would be desirable if the library could admit fluents that are not fully specified, trusting the user that the undefined values are not relevant.

**To Reproduce**
```
#!/usr/bin/env python3

from unified_planning.shortcuts import *
from unified_planning.io import PDDLReader

reader = PDDLReader()
domain_filename = "./downward-benchmarks/transport-opt11-strips/domain.pddl"
problem_filename = "./downward-benchmarks/transport-opt11-strips/p01.pddl"

problem = reader.parse_problem(domain_filename, problem_filename)

with  OneshotPlanner(names=['fast-downward']) as planner:
    final_report = planner.solve(problem)
```

**Result of the above script**
```
Traceback (most recent call last):
  File "/home/alvaro/teaching/phd-planning/src/./demo-load.py", line 14, in <module>
    final_report = planner.solve(problem)
  File "/home/alvaro/.local/lib/python3.10/site-packages/unified_planning/engines/mixins/oneshot_planner.py", line 80, in solve
    return self._solve(problem, heuristic, timeout, output_stream)
  File "/home/alvaro/.local/lib/python3.10/site-packages/unified_planning/engines/parallel.py", line 138, in _solve
    final_reports = self._run_parallel("solve", problem, timeout, None)
  File "/home/alvaro/.local/lib/python3.10/site-packages/unified_planning/engines/parallel.py", line 108, in _run_parallel
    raise res
unified_planning.exceptions.UPProblemDefinitionError: Initial value not set for fluent: road-length(city-1-loc-1, city-1-loc-1)
```

**Comment by mikand** [comment]
Dear @alvaro-torralba,
this is a known limitation of the library (that should be better documented). We discussed at length if and how to support the PDDL "undefined", but we realized that the semantics is not uniform among planning engines (and validators). So, for now, the library insists in having a fully-specified initial-state, including numeric fluents. 

If you are curious, the semantic issue is on the interpretation of preconditions having an "undefined", according to the standard any condition containing an undefined value should be unsatisfied (even a "true or undefined >= 0"), but many planners and even validators disagree on this semantics.

@hstairs maybe we shall report the results of our experiments somewhere in the documentation

**Comment by alvaro-torralba** [comment]
Thanks Andrea for the quick reply. 

I agree, I would consider any domain where the values are used in the preconditions to be ill-formed. The point is that in this case, the numeric fluents only refers to the action cost of actions that are non-applicable due to static preconditions, so the undefined values are not really relevant.  However, I see how from the point of the library it may be difficult to check automatically whether these values are needed or not. 

I have a suggestion to address this issue: 
- Add an additional attribute to the problem description that corresponds to the value of undefined numerical literals. By default, this value should be None, but the user of the library can overwrite it (e.g. with a setter or when parsing the domain and problem file).
- When the value is accessed, if the fluent is undefined, then the default value is returned. If the default value is None, an exception is thrown. 

The advantages of this method is that the behaviour of the library would not be affected at all unless the user specifies such a default value. And, in cases where the user wants to specify a value of 0, or 1, or 10000, they are able to influence the semantics. For loading the transport domain, the user could then specify any value, as we know the value is irrelevant, and then the library can work with such domain.  

I'm not 100% familiar with the code of the library yet, do you think what I describe above could work or am I missing something?

**Comment by hstairs** [comment]
@mikand You mean what we observed that some planners were disagreeing on the semantics of undefined numeric variables?

**Comment by alvalentini** [comment]
Currently, a possible solution is to add a default value after the parsing in this way:

```python
from unified_planning.shortcuts import *
from unified_planning.io import PDDLReader

reader = PDDLReader()
domain_filename = "./downward-benchmarks/transport-opt11-strips/domain.pddl"
problem_filename = "./downward-benchmarks/transport-opt11-strips/p01.pddl"

problem = reader.parse_problem(domain_filename, problem_filename)

expression_manager = problem.environment.expression_manager
problem.fluents_defaults[problem.fluent("road-length")] = expression_manager.Int(-1)

with  OneshotPlanner(names=['fast-downward']) as planner:
    final_report = planner.solve(problem)
```
