### ISSUE TITLE
Serializable problem description format

### ISSUE THREAD

**Issue by arbimo** [aiplan4eu/unified-planning#53]
### User Story
As a **technology provider** I want to be able to load the problem definition and solver configuration from structured data.

The UPF allows constructing planning problems from both a python API or by parsing a problem definition in a supported input language (currently PDDL). The problem is loaded in memory in the UPF. Currently to call a planner, the UPF can either rely on the planner's python binding or export the problem to PDDL.

PDDL as language for exchanging the description of planning problem is limiting as the UPF allows specifying constructs that do not directly map to PDDL (e.g. ICE in #45). On the other hand, relying on the python API strongly couples the UPF with a particular version of the solver and complicates distribution.

Having a specialized data structure that fully represents the planning problem would enable planners to support the the native features of the UPF while running in a separate process.
As a planner developer, it would allow decoupling the planner's implementation and the UPF development, with the ability to test the planner on problems constructed with the UPF without directly depending on it.

### Acceptance Criteria

- [ ] The problem description format is independent from any programming language (e.g. JSON or protobuf)
- [ ] The problem description format can be serialized, either to be written to a file or to be sent over the network to planner running in another process.
- [ ] The problem description format is extensible, with parts of the schema being explicitly linked to particular features (e.g. hierarchies, ...)

### Attention Points

- Backward compatibility of the problem description format is important. Extensions to the schema should be backward compatible and it should be possible to compile away the cutting edge features to a smaller/earlier schema version. This needs to be kept in mind but is not necessary for prototyping phase.

**Comment by uwe-koeckemann** [comment]
Below is the output of the direct translation UPF to AIDDL (a general purpose DDL for hybrid/integrated AI systems, see aiddl.org) of one of the UPF test cases. This can currently be parsed in Python, Java, and Scala. With a bit of work (simplifying expressions where possible) this could be a candidate to provide a DDL to the UPF and it would allow to combine the UPF easily with other types of AI problems.

However, I think for the purpose of just serialization (less human readable), YAML or JSON may be better because parsers are more widely available.  

```
(
  name:"robot_loader_adv"
  fluents:
    [
      (robot_at bool [Robot Location])
      (cargo_at bool [Container Location])
      (cargo_mounted bool [Container Robot])
    ]

  objects:[(r1 Robot) (l1 Location) (l2 Location) (l3 Location) (c1 Container)]
  actions:
    [
      (
        name:move
        params:[?l_from ?l_to ?r]
        param-types:[Location Location Robot]
        preconditions:
          [
            (
              NOT
              [(EQUALS [(PARAM_EXP aparam:?l_from) (PARAM_EXP aparam:?l_to)] none:-)]
              none:-
            )

            (FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?l_from)] fluent:robot_at)
            (
              NOT
              [(FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?l_to)] fluent:robot_at)]
              none:-
            )

          ]

        effects:
          [
            (FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?l_from)] fluent:robot_at):
              (BOOL_CONSTANT bool:False)
            (FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?l_to)] fluent:robot_at):
              (BOOL_CONSTANT bool:False)
          ]

      )

      (
        name:load
        params:[?loc ?r ?c]
        param-types:[Location Robot Container]
        preconditions:
          [
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?loc)] fluent:cargo_at)
            (FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?loc)] fluent:robot_at)
            (
              NOT
              [
                (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?r)] fluent:cargo_mounted)
              ]

              none:-
            )

          ]

        effects:
          [
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?loc)] fluent:cargo_at):
              (BOOL_CONSTANT bool:False)
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?r)] fluent:cargo_mounted):
              (BOOL_CONSTANT bool:False)
          ]

      )

      (
        name:unload
        params:[?loc ?r ?c]
        param-types:[Location Robot Container]
        preconditions:
          [
            (
              NOT
              [(FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?loc)] fluent:cargo_at)]
              none:-
            )

            (FLUENT_EXP [(PARAM_EXP aparam:?r) (PARAM_EXP aparam:?loc)] fluent:robot_at)
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?r)] fluent:cargo_mounted)
          ]

        effects:
          [
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?loc)] fluent:cargo_at):
              (BOOL_CONSTANT bool:False)
            (FLUENT_EXP [(PARAM_EXP aparam:?c) (PARAM_EXP aparam:?r)] fluent:cargo_mounted):
              (BOOL_CONSTANT bool:False)
          ]

      )

    ]

  initialState:
    [
      (FLUENT_EXP [(OBJECT_EXP obj:r1) (OBJECT_EXP obj:l1)] fluent:robot_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:r1) (OBJECT_EXP obj:l2)] fluent:robot_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:r1) (OBJECT_EXP obj:l3)] fluent:robot_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:c1) (OBJECT_EXP obj:l1)] fluent:cargo_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:c1) (OBJECT_EXP obj:l2)] fluent:cargo_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:c1) (OBJECT_EXP obj:l3)] fluent:cargo_at):
        (BOOL_CONSTANT bool:False)
      (FLUENT_EXP [(OBJECT_EXP obj:c1) (OBJECT_EXP obj:r1)] fluent:cargo_mounted):
        (BOOL_CONSTANT bool:False)
    ]

  goals:
    [
      (FLUENT_EXP [(OBJECT_EXP obj:c1) (OBJECT_EXP obj:l3)] fluent:cargo_at)
      (FLUENT_EXP [(OBJECT_EXP obj:r1) (OBJECT_EXP obj:l1)] fluent:robot_at)
    ]
)
```

**Comment by mikand** [comment]
I think we can easily construct a printer/parser in json/yaml (actually Json is a subset of yaml 1.2) that is sufficiently human readable.
If we need speed, I think that the Protobuf format (see also #48) should be more efficient in time and space, but also not human readable.
Both these approaches work with virtually any programming language.
