### ISSUE TITLE
Cleanup temp directory after generating plans.

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#537]
Removing the `temp` directory after generating the plans will be better. Note that generating lots of plans without cleaning such a directory will take more inodes, which will impact the filesystem and would easily lead to consuming all inodes, preventing the system from creating new files.

The change is simple and can be done at [this line](https://github.com/aiplan4eu/unified-planning/blob/d08701bf89887cd2250ccd73a441be86b18cc2f5/unified_planning/engines/pddl_planner.py#L175):

```
tmpdir = tempfile.TemporaryDirectory()
# Do the planning stuff

# Invoke cleanup after solving the planning task.
tmpdir.cleanup()
```

Thanks @speckdavid  for highlighting this.

**Comment by alvalentini** [comment]
We use the `tempfile` with the `with` statement. It automatically deletes the directory at the end.

See [here](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) and [here](https://docs.python.org/3/library/tempfile.html#tempfile-examples).

**Comment by MFaisalZaki** [comment]
This makes sense. Thanks a lot for highlighting this.
