### ISSUE TITLE
Issue with "symk-opt" in a simple navigation problem

### ISSUE THREAD

**Issue by Alelafar** [aiplan4eu/unified-planning#551]
I modeled a simple navigation problem.

We start from a weighted graph with a starting node where it is a robot and each weight for edges represents the cost of the movement of the robot. Moreover, in some nodes there are packages and our objective is to find the path with the lowest cost in order to let the robot moving the packages from their positions to target positions given initially. In any node there can be at most one pack.

When I try to solve the problem optimally, the planner "enhsp-opt" can find a plan which its final cost is equal to 19. On the other hand, the planner "symk-opt" still finds an "optimal" solution but its cost is equal to 29.

It is clear that there is a problem. I don't know if I did something wrong or if there is a problem with "symk-opt" solution, since it is possible to find a better solution.

In the file attached there is my code where I generate the weighted graph, create the problem and compare the solutions between the two planners.

[Problem_symk-opt.txt](https://github.com/aiplan4eu/unified-planning/files/13706765/Problem_symk-opt.txt)

**Comment by Framba-Luca** [comment]
@speckdavid maybe you can help on this

**Comment by speckdavid** [comment]
Thanks for reporting this. There was an issue in the pipeline of `up-symk`. The cost of the actions were always ignored and the length of the plan was actually optimized instead of the cost of the plan. With the [version 1.1.0](https://pypi.org/project/up-symk/) it should be fixed.

Please let me know if you encounter any other problems.

**Comment by Alelafar** [comment]
It is fixed! Thank you :)
