### ISSUE TITLE
Implementation of `__eq__` and `__hash__` for `UPState`

### ISSUE THREAD

**Issue by IreneBrugnara** [aiplan4eu/unified-planning#555]
It would be useful to implement the methods `__eq__` and `__hash__` for class `UPState` in order to use states as keys of dictionaries. That would be useful when applying reinforcement learning algorithms using `SequentialSimulator` for constructing the rollouts, in order to map states to their value function.
The same functionality would be useful also for class `ActionInstance` in order to implement state-action value functions. However, the functionality of `__eq__` is already provided by the method `is_semantically_equivalent`.

**Comment by fteicht** [comment]
Hi @IreneBrugnara 
If you are interested, it is actually what we have done in the Unified Planning interface to [scikit-decide](https://github.com/airbus/scikit-decide), which allows us to run simulation-based algorithms (e.g. MCTS, IW) or search algorithms (e.g. A*) or Reinforcement Learning algorithms (e.g. DQN, PPO) on Unified Planning problems.
See [here](https://github.com/airbus/scikit-decide/blob/master/skdecide/hub/domain/up/up.py) and more specifically our implementation of the [SkUPState](https://github.com/airbus/scikit-decide/blob/e93ab7b9315b35be06e6658602c5bb5b1e46ba40/skdecide/hub/domain/up/up.py#L32) and [SkUpAction](https://github.com/airbus/scikit-decide/blob/e93ab7b9315b35be06e6658602c5bb5b1e46ba40/skdecide/hub/domain/up/up.py#L84) classes.

**Comment by IreneBrugnara** [comment]
Interesting, thanks!

**Comment by alvalentini** [comment]
Solved in #579
