### ISSUE TITLE
ParseException when using parse_problem_string()

### ISSUE THREAD

**Issue by CJRzzZ** [aiplan4eu/unified-planning#573]
I met ParseException when using parse_problem_string() to import the problem in PDDL format. 
![image](https://github.com/aiplan4eu/unified-planning/assets/69406967/d2e9148e-44bb-4a27-9d81-bb13b5ef0818)

The file is from the ENHSP repo as an example and it gave ParseException: , found '('  (at char 280), (line:19, col:5). As I checked line 19 of the domain file it seems nothing wrong.
![image](https://github.com/aiplan4eu/unified-planning/assets/69406967/079c0ed2-ab1c-4aea-9527-78149a92b921)

The domain and problem file are in the attachment, could you please tell me what's going wrong? Thanks in advance.
[car.zip](https://github.com/aiplan4eu/unified-planning/files/14397931/car.zip)

**Comment by alvalentini** [comment]
Hi @CJRzzZ! This is a PDDL+ problem with processes and events and they are currently not supported by the `unified-planning` library.

**Comment by alvalentini** [comment]
You are right! It isn't clearly documented the PDDL features supported.. however the features up to PDDL 2.2 should be quite well supported.
