### ISSUE TITLE
Issue with Plus (+) Expression Handling Multiple Arguments in ANML

### ISSUE THREAD

**Issue by carladavesa** [aiplan4eu/unified-planning#587]
Hello,

The Plus expression in Unified Planning is expected to handle more than two arguments, such as Plus(a, b, c) or Plus([a, b, c]). However, during the conversion process from PDDL to ANML, the handling of this expression seems to be incorrect. ANML throws an error, stating that it only accepts a fixed number of two arguments.

The expected behavior is to sum all the provided arguments, giving preference to summing from left to right.

![image](https://github.com/aiplan4eu/unified-planning/assets/80886646/9deccc72-5d1b-4646-98ef-08e759f8a230)

![image](https://github.com/aiplan4eu/unified-planning/assets/80886646/a022b7af-c7ac-49c5-b587-b059e9bf44b2)

**Desktop:**
 - OS: macOS Sonoma
 - Browser: safari
 - Version: 14.0

**Comment by mikand** [comment]
@alvalentini It looks like a bug in `up-tamer`...

**Comment by alvalentini** [comment]
Yes! I'll fix it asap

**Comment by alvalentini** [comment]
This issue should be fixed updating `up-tamer` to version `1.1.3`
