### ISSUE TITLE
Planning taxonomy

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#6]
An initial version of the taxonomy is reported [here](../wiki/Planning-Taxonomy). This issue is for discussions and improvements to the taxonomy.

**Comment by haz** [comment]
Broken link?

**Comment by haz** [comment]
CC @nirlipo

**Comment by nirlipo** [comment]
Great! to see this taxonomy. Would you like us to propose some edits? After a quick read, I can push these edits if you want:

- adding a section about dynamics or action effects:
  - instantaneos
  - continous
  - both

- I would also change MCTS -> Online planning or lookaheads

- And I'm happy to add more tools to the list: VAL, POPF, Tarski, LAPKT, SHOP2, etc.

**Comment by mikand** [comment]
@nirlipo Sorry for the latency, somehow I was not notified of your comment!

Absolutely, If you have ideas suggestions they are super-welcome.
You can directly edit & create a PR for `docs/wiki`

**Comment by haz** [comment]
Heya! So first thoughts...
- Can cross reference everything at https://github.com/ai-planning/ and https://planning.wiki/ref/planners 
- Should almost certainly cross-reference with the known `:requirements` options in common PDDL
- Might want to break down the problem characterization based on state -vs- action properties (e.g., partially observable -vs- non-deterministic)

**Comment by mikand** [comment]
We reported the current "taxonomy" of features supported (an automatically detected) by the UP in the docs here: https://unified-planning.readthedocs.io/en/latest/problem_representation.html#problem-kinds
