### ISSUE TITLE
'expression not well-formed' error when parsing PDDL

### ISSUE THREAD

**Issue by LBonassi95** [aiplan4eu/unified-planning#75]
**Bug description**
The upf crashes when parsing some PDDL instances. 

**To reproduce**
```python
import upf
from upf.shortcuts import *
from upf.io.pddl_reader import PDDLReader

reader = PDDLReader()
pddl_problem = reader.parse_problem('domain.pddl', 'p01.pddl')
 ```

This snippet of code produces the following error: 
``` UPFTypeError: The expression '(at(t, m) and loaded(g, t, l3) and ready-to-load(g, m, l2) and next(l2, l1) and next(l4, l3))' is not well-formed ```

PDDL files: [pddl_files.zip](https://github.com/aiplan4eu/upf/files/7951796/pddl_files.zip)

**Expected behavior**

The ```pddl_problem``` is instantiated correctly.

**Environment**
 - OS: Ubuntu 20.04.3 LTS
 - Python version: 3.8.12

**Comment by mikand** [comment]
Thanks for the report @LBonassi95!

@alvalentini can you have a look?

**Comment by alvalentini** [comment]
Currently in the UPF we don't support type hierarchy, and this PDDL instance has it.
We should probably raise a clearer error before the creation of the expressions.

**Comment by alvalentini** [comment]
This issue is now fixed in master!
