### ISSUE TITLE
Improving on the interface after planning to interpret additional planner output

### ISSUE THREAD

**Issue by hstairs** [aiplan4eu/unified-planning#76]
The Unified Planning Framework should be able to have some feature to get additional information after the planner has done its task. This may be related to both the case where the planner has not been able to find a solution and the case where the planner did find a solution. For the former, additional information explaining the reasons of the failure are desirable, like memory crash, instance proved unsolvable so on and so forth. For the latter, additional information could include statistics of the planner, or the cost of the found solution.
@mikand that perhaps we can have a more structured data type for the result of the planner.

**Comment by arbimo** [comment]
Just to mention that I made a related proposal for the gRPC interface in PR #78.
The `Stopped` message essentially encode the data returned by the planner, independently of any plan provided previously.

Needless to say, this should match almost one-to-one with what is expressible with the python API so it might a good place to discuss it based on a concrete format ;)

**Comment by hstairs** [comment]
Hi, I saw your proposal, thanks! It seems it contains all the necessary data fields. What are the next steps then to get the UP to actually exposes these features so that they can be used also by planners that do not adopt a gRPC interface? @mikand ?

**Comment by madmage** [comment]
I guess we should first talk about the timeline of the features we intend to include in the UP. What features come first? What is really necessary? A prioritized list of features should be published somewhere, I think. It could be also important for us to contribute to the discussions and maybe to the implementation.
The protobuf definition, being something used to expose features in the UP, should follow this development. I don't see it good to provide the full protobuf API first (as stubs) and then start implementing (maybe) the features in the UP.
Moreover, I see there is already a page with a Taxonomy https://github.com/aiplan4eu/unified-planning/wiki/Planning-Taxonomy that we can use to split the topics and start discussing/prioritizing the features.

**Comment by madmage** [comment]
Just to summarize, in this issue we are actually asking the UP to provide in the final output of the planner, the following additional fields, as requested by the OP of this issue and by the gRPC proposal (https://github.com/aiplan4eu/unified-planning/pull/78/files)"

- metrics (as in the OP and in the gRPC API proposal), for example (this is what we currently have, just to have concrete examples) time spent planning or number of states visited
- reason of failure (in case of failure), some of them are listed in the gRPC API proposal in the Stopped message (do we need two separate messages Report and Stopped? isn't it enough to put everything in the same planner output response?)
  - no plan exists
  - search space exhausted
  - timeout
  - out of memory
  - internal error
  - etc.

is it correct?

do we need an additional message for the output of the planner "while" it is planning (https://github.com/aiplan4eu/unified-planning/issues/77)?

**Comment by arbimo** [comment]
>     * reason of failure (in case of failure), some of them are listed in the gRPC API proposal in the Stopped message (do we need two separate messages Report and Stopped? isn't it enough to put everything in the same planner output response?)

The `Stopped` message is essentially the final report (subject of this issue) while the `Report` message is aimed as an intermediate report while planning (subject of #77 and also mentioned in the plan quality discussion #69). Me might want to rename them to clarify their usage (e.g. `FinalReport` and `IntermediateReport`)

The name of the `metrics` field is perhaps a bit specific : while we can expect it to be used primarily for metrics there might be other kinds of information  provided such as the type of search used, ...
