### ISSUE TITLE
Improving on the interface "while" planning to interpret additional planner output

### ISSUE THREAD

**Issue by hstairs** [aiplan4eu/unified-planning#77]
Establish some mechanism for letting the Unified Planning Framework able to inspect the output of the planner whilst the planner is actually planning. For instance, the planner maybe able to say when it has done preprocessing, or some estimation of the heuristic while planning that gives some notion of progress.
It has been noticed that this is likely to be very planner specific, and @arbimo suggested that at the moment we may as well just give the ability to read the standard output of the planner. Bit low level, but can be useful for some use case.

**Comment by alvalentini** [comment]
This issue should be fixed in #94
