### ISSUE TITLE
Inconsistent use of @property

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/unified-planning#80]
Within the library sometimes we use `@property` to create non-parametric getters, sometimes not.

For example:

- In `Environment` we use `@property`
- In model, most of the times we use plain methods (e.g. `IntType.lower_bound()`, )
- In `Problem` we have `name` which is a `@property` again
- Fluents use plain methods (`f.name()`) while actions have the property (`a.name`)

I think this is quite confusing for the user and shall be uniformed.

**Comment by madmage** [comment]
I would add that the GitHub repo is called unified-planning, while the Python module is called unified_planning (with the underscore). Just to avoid confusion, I would use the same name for both (I suggest unified_planning, since dashes are bad for a Python repo).

**Comment by madmage** [comment]
I would add that in `Action` we have "a.name" that is a property (with a setter), while the cost is read with `cost()` and set with `set_cost()`.

**Comment by alvalentini** [comment]
This issue should be fixed in #116
