### ISSUE TITLE
Reason for the planner as context manager (with)

### ISSUE THREAD

**Issue by madmage** [aiplan4eu/unified-planning#86]
I was wondering why the planners are designed as context managers (i.e. it is possible to use them in a `with` statement). Apart from the very simple case:

```
with OneshotPlanner(name="tamer") as planner:
    plan = planner.solve(problem)
```

That can be easily written as:
```
planner = OneshotPlanner(name="tamer")
plan = planner.solve(problem)
```

I do not see any other examples that can make me understand the use-case. In particular, I don't see how this can extend to other kinds of planners (e.g. anytime planners or planners that survive the single `solve` call because they need to keep information).

**Comment by mikand** [comment]
The current operation modes are reentrant, so you could get away without with statement by creating and destroying all the resources within the `solve`/`validate` methods.

We envisioned operation modes (e.g. Replanning) that are not reentrant, meaning that the planner needs to keep some info and perform cleanup operations when the object is released hence justifying the `with`.

Currently, some planners (e.g. tamer) acquire the resources in construction and release it in the `__exit__`.

**Comment by madmage** [comment]
The planner has to release resources after exiting the `with` context or, more generally, when the object is destroyed? What kind of resources are we talking about?

What I have in mind is a planner object (that keeps all the resources, partial plans, etc.) that survives many cycles of the main loop of the system (because I am thinking of an existent system where all the loops are already defined) and thus the `with` statement does not apply. I am not saying that the two use-cases cannot co-exist, I was just trying to understand for what reason the planner class has been designed with a `with`-statement in mind... as well as to take into account that the code at the `__exit__` must be also called when the object is destroyed, either explicitly and implicitly, to support other use cases (and the same applies to the `__enter__` and construction/setup of the object).

**Comment by mikand** [comment]
@madmage We now have a `destroy()` method that can be explicitly called by the user if the engine is not istantiated via a context manager:
```python
p = OneshotPlanner(...)
...
p.destroy()
```
Note that the invocation is manual and not automatic, as the garbage collection of Python is not reliable in terms of _when_ the object is eventually destroyed.
