### ISSUE TITLE
Provide a release tag

### ISSUE THREAD

**Issue by onjen** [aiplan4eu/unified-planning#88]
At Magazino we're currently looking into packaging this repository. It would be great to have a tagged version to start with. Are you planning to do releases at some point?

**Comment by mikand** [comment]
@onjen Yes. Actually, we are planning to put this on pypi so that it can be installed directly with `pip`.
How urgent is this for you? If needed, we can prioritize this.

**Comment by madmage** [comment]
What @onjen is asking is just a tag in the current repository, with a proper "release" syntax (we currently have only [D3.2](https://github.com/aiplan4eu/unified-planning/releases/tag/D3.2)), not to rely on the moving master branch, but on a fixed point in time (0.0.1 could be fine).

**Comment by onjen** [comment]
Yep, that looks good :+1: 

Regarding the urgency, it would be great to have a tagged version somewhere around end of March beginning of April. But that of course depends on your plans :)

**Comment by mikand** [comment]
Excellent. I think we can do it next week already. Thanks for signaling the issue, I'll keep this open until we have the versioning in place.

**Comment by madmage** [comment]
Hi. Any news about this?

**Comment by onjen** [comment]
yes, thank you!
