### ISSUE TITLE
Planner supports() and asserts

### ISSUE THREAD

**Issue by madmage** [aiplan4eu/unified-planning#93]
I see that the `Solver` interface has a `supports()` method to establish if the solver can solve the problem.
I see that tamer (up-tamer) checks for (asserts) this before starting solving the problem, while pyperplan (up-pyperplan) has the correct `supports()` function, but it is not used. Wouldn't it make sense to _always_ (i.e. from the interface itself) check this, instead of demanding the check to the single implementations?

**Comment by mikand** [comment]
This is reasonable. 

However, we need to intercept the call to the operation modes and this causes a slight change in the Engine. @alvalentini will work on this (since we already broke backward compatibility anyway 😆 )
